# Generated by Django 2.2.9 on 2020-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='belongs_to',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='camera_make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='camera_model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='exposure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='f_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='filesize',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='focal_length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='iso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='src',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumb',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pathmodel',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
